#!/bin/bash
docker cp tasks/wordcount-mapreduce.sh hadoop-master:/root/wordcount-mapreduce.sh
docker exec -it hadoop-master /root/wordcount-mapreduce.sh

docker cp tasks/wordcount-spark.sh spark:/root/wordcount-spark.sh
docker exec -it spark /root/wordcount-spark.sh