#!/bin/bash

# get number of cluster nodes
NODES=${1:-3}

# get version of hadoop or fallback to 2.7.2
VERSION=${2:-2.7.2}

if [[ "$(docker images -q $(whoami)/hadoop:$VERSION 2> /dev/null)" == "" ]]; then
  # do something
  echo -e "docker image not found!\nbuild a new one...\n"
  cd hadoop-build
  ./build $NODES $VERSION
  cd ..
fi

# start hadoop master container
docker rm -f hadoop-master &> /dev/null
echo "start hadoop-master container..."
docker run -itd \
                --net=hadoop \
                -p 50070:50070 \
                -p 8088:8088 \
                --name hadoop-master \
                --hostname hadoop-master \
                $(whoami)/hadoop:$VERSION

# start hadoop slaves containers
i=1
while [ $i -lt $NODES ]
do
	docker rm -f hadoop-slave$i &> /dev/null
	echo "start hadoop-slave$i container..."
	docker run -itd \
	                --net=hadoop \
	                --name hadoop-slave$i \
	                --hostname hadoop-slave$i \
	                $(whoami)/hadoop:$VERSION
	i=$(( $i + 1 ))
done 

# start hadoop inside container
docker exec -it hadoop-master /root/start-hadoop.sh

# execute computation
docker exec -it hadoop-master /root/wordcount.sh
